version: "3.9"
services: 
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./back/database
    links:
      - mongodb
  
  back:
    build: ./back
    depends_on: 
      - mongodb